/*--------------------------------------------------------------------
 * Author: Martin Corino
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the R2CORBA LICENSE which is
 * included with this program.
 *
 * Copyright (c) Remedy IT Expertise BV
 *--------------------------------------------------------------------*/

/// Put the interfaces in a module, to avoid global namespace pollution
module Test
{
  /// A very simple interface
  interface Hello
  {
    /// Return a simple string
    string echo (in string method, in string message);

    /// A method to shutdown the ORB
    /**
     * This method is used to simplify the test shutdown process
     */
    oneway void shutdown ();
  };
};
