/*--------------------------------------------------------------------
 * Author: Martin Corino
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the R2CORBA LICENSE which is
 * included with this program.
 *
 * Copyright (c) Remedy IT Expertise BV
 * Chamber of commerce Rotterdam nr.276339, The Netherlands
 *--------------------------------------------------------------------*/

valuetype BaseNode
{
  public BaseNode left;
  public BaseNode right;
};

valuetype StringNode : BaseNode
{
  public string name;
};

valuetype TreeController
{
  public BaseNode root;
};

interface passer
{
  void pass_tree (out TreeController outarg);
  oneway void shutdown ();
};
