name: Ruby Gem Release

on:
  release:
    types: [published]

jobs:
  build:
    name: Publish
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'
    - name: Publish to RubyGems
      run: |
        rake gem
        rake r2corba:gem:taogem
        gem push pkg/r2corba*.gem
        gem push pkg/taosource*.gem
      env:
        GEM_HOST_API_KEY: ${{secrets.RUBYGEMS_API_KEY}}
