name: linux

on:
  push:
  pull_request:
  schedule:
    - cron: '0 7 * * SUN'

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-20.04
            ruby: 'jruby'
            jacorb_version: '3.9'
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} jruby-jacorb-${{ matrix.jacorb_version }}
    env:
      DOC_ROOT: ${{ github.workspace }}/ACE_TAO
      JACORB_HOME: ${{ github.workspace }}/jacorb
      RIDL_ROOT: ${{ github.workspace }}/ridl
    steps:
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: checkout r2corba
      uses: actions/checkout@v2
    - name: checkout ACE_TAO
      uses: actions/checkout@v2
      with:
        repository: DOCGroup/ACE_TAO
        path: ${{ env.DOC_ROOT }}
        ref: Latest_ACE7TAO3_Micro
    - name: checkout MPC
      uses: actions/checkout@v2
      with:
        repository: DOCGroup/MPC
        path: ${{ env.MPC_ROOT }}
        ref: Latest_ACE7TAO3_Micro
    - name: checkout ridl
      uses: actions/checkout@v2
      with:
        repository: RemedyIT/ridl
        path: ${{ env.RIDL_ROOT }}
    - name: Add Repo
      run: |
        wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add -
        sudo apt-add-repository "deb http://apt.llvm.org/$(lsb_release -cs)/ ${{ matrix.Repo }} main"
      if: matrix.Repo != ''
    - name: Add packages
      run: |
        sudo apt-get --yes update
        sudo apt-get --yes install ${{ matrix.PackageDeps }}
    - name: Download a file
      uses: carlosperate/download-file-action@v1.0.3
      id: download-jacorb
      with:
        file-url: 'https://www.jacorb.org/releases/${{ matrix.jacorb_version }}/jacorb-${{ matrix.jacorb_version }}-binary.zip'
        file-name: 'jacorb-${{ matrix.jacorb_version }}.zip'
        location: '${{ github.workspace }}'
    - uses: montudor/action-zip@v0.1.1
      with:
        args: unzip -qq jacorb-${{ matrix.jacorb_version }}.zip -d jacorb
    - name: Run rake configure
      run: |
        ls -al
        rake configure
      shell: pwsh
    - name: Run rake build
      run: |
        rake build
      shell: pwsh
    - name: Run rake test
      run: |
        rake test
      shell: pwsh
