name: linux

on:
  push:
  pull_request:
  schedule:
    - cron: '0 7 * * SUN'

jobs:
  build:
    strategy:
      matrix:
        include:
          - CC: gcc-4.8
            CXX: g++-4.8
            PackageDeps: g++-4.8
            os: ubuntu-16.04
            ruby: '2.4'
          - CC: gcc-6
            CXX: g++-6
            PackageDeps: g++-6
            os: ubuntu-18.04
            ruby: '2.5'
          - CC: gcc-7
            CXX: g++-7
            PackageDeps: g++-7
            os: ubuntu-18.04
            ruby: '2.6'
          - CC: gcc-8
            CXX: g++-8
            PackageDeps: g++-8
            os: ubuntu-18.04
            ruby: '2.7'
          - CC: gcc-9
            CXX: g++-9
            PackageDeps: g++-9
            os: ubuntu-20.04
            ruby: '2.7'
          - CC: gcc-10
            CXX: g++-10
            PackageDeps: g++-10
            os: ubuntu-20.04
            ruby: '2.7'
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} ${{ matrix.CXX }} ruby-${{ matrix.ruby }}
    env:
      DOC_ROOT: ${{ github.workspace }}/ACE_TAO
      ACE_ROOT: ${{ github.workspace }}/ACE_TAO/ACE
      TAO_ROOT: ${{ github.workspace }}/ACE_TAO/TAO
      MPC_ROOT: ${{ github.workspace }}/ACE_TAO/MPC
      RIDL_ROOT: ${{ github.workspace }}/ridl
      CC: ${{ matrix.CC }}
      CXX: ${{ matrix.CXX }}
    steps:
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: checkout r2corba
      uses: actions/checkout@v2
    - name: checkout ACE_TAO
      uses: actions/checkout@v2
      with:
        repository: DOCGroup/ACE_TAO
        path: ${{ env.DOC_ROOT }}
        ref: Latest_Micro
    - name: checkout MPC
      uses: actions/checkout@v2
      with:
        repository: DOCGroup/MPC
        path: ${{ env.MPC_ROOT }}
        ref: Latest_ACETAO_Micro
    - name: checkout ridl
      uses: actions/checkout@v2
      with:
        repository: RemedyIT/ridl
        path: ${{ env.RIDL_ROOT }}
    - name: Add Repo
      run: |
        wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add -
        sudo apt-add-repository "deb http://apt.llvm.org/$(lsb_release -cs)/ ${{ matrix.Repo }} main"
      if: matrix.Repo != ''
    - name: Add packages
      run: |
        sudo apt-get --yes update
        sudo apt-get --yes install ${{ matrix.PackageDeps }}
    - name: Run rake configure
      run: |
        rake configure
      shell: pwsh
    - name: Run rake build
      run: |
        rake build
      shell: pwsh
    - name: Run rake test
      run: |
        rake test
      shell: pwsh
