name: windows

on:
  push:
  pull_request:
  schedule:
    - cron: '0 7 * * SUN'

jobs:
  build:
    runs-on: windows-2019
    strategy:
      matrix:
        include:
          - msystem: MINGW64
            arch: x86_64
            platform_file: include $(ACE_ROOT)/include/makeinclude/platform_mingw32.GNU
            ruby: '2.1'
          - msystem: MINGW64
            arch: x86_64
            platform_file: include $(ACE_ROOT)/include/makeinclude/platform_mingw32.GNU
            ruby: '2.2'
    name: ${{ matrix.runs-os }} ${{ matrix.msystem }} ruby-${{ matrix.ruby }}
    env:
      DOC_ROOT: ${{ github.workspace }}/ACE_TAO
      ACE_ROOT: ${{ github.workspace }}/ACE_TAO/ACE
      TAO_ROOT: ${{ github.workspace }}/ACE_TAO/TAO
      MPC_ROOT: ${{ github.workspace }}/ACE_TAO/MPC
      RIDL_ROOT: ${{ github.workspace }}/ridl
    steps:
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: checkout r2corba
      uses: actions/checkout@v2
    - name: checkout ACE_TAO
      uses: actions/checkout@v2
      with:
        repository: DOCGroup/ACE_TAO
        path: ${{ env.DOC_ROOT }}
        ref: Latest_ACE7TAO3_Micro
    - name: checkout MPC
      uses: actions/checkout@v2
      with:
        repository: DOCGroup/MPC
        path: ${{ env.MPC_ROOT }}
        ref: Latest_ACE7TAO3_Micro
    - name: checkout ridl
      uses: actions/checkout@v2
      with:
        repository: RemedyIT/ridl
        path: ${{ env.RIDL_ROOT }}
    - uses: msys2/setup-msys2@v2
      with:
        msystem: ${{ matrix.msystem }}
        install: make
    - run: pacman --noconfirm -S mingw-w64-${{ matrix.arch }}-gcc
      shell: msys2 {0}
    - name: Run rake configure
      run: |
        export ACE_ROOT=`cygpath -u $ACE_ROOT`
        export TAO_ROOT=`cygpath -u $TAO_ROOT`
        export MPC_ROOT=`cygpath -u $MPC_ROOT`
        rake configure
      shell: msys2 {0}
    - name: Run rake build
      run: |
        rake build
      shell: msys2 {0}
    - name: Run rake test
      run: |
        export ACE_ROOT=`cygpath -u $ACE_ROOT`
        rake test
      shell: msys2 {0}
